-- AlterTable
ALTER TABLE "User" ADD COLUMN     "isBot" SMALLINT NOT NULL DEFAULT 0,
ALTER COLUMN "lastName" DROP NOT NULL,
ALTER COLUMN "email" DROP NOT NULL,
ALTER COLUMN "password" DROP NOT NULL,
ALTER COLUMN "genderId" DROP NOT NULL;
